[workspace]
resolver = "3"
members = [
    "crates/app",
    "crates/core",
    "crates/fs-local",
    "crates/operations",
    "crates/preview",
    "crates/ui-gtk",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.85"

[workspace.dependencies]
gio = { version = "0.21", features = ["v2_72"] }
gdk-pixbuf = "0.21"
glib = "0.21"
gtk = { package = "gtk4", version = "0.10", features = ["v4_12"] }
pathpilot-core = { path = "crates/core" }
pathpilot-fs-local = { path = "crates/fs-local" }
pathpilot-operations = { path = "crates/operations" }
pathpilot-preview = { path = "crates/preview" }
pathpilot-ui-gtk = { path = "crates/ui-gtk" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tempfile = "3"
syntect = { version = "5.3", default-features = false, features = ["default-fancy"] }
pulldown-cmark = { version = "0.13.4", default-features = false }
