[package]
name = "pathpilot-ui-gtk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
adw.workspace = true
gio.workspace = true
glib.workspace = true
gtk.workspace = true
pathpilot-core.workspace = true
pathpilot-config.workspace = true
pathpilot-fs-local.workspace = true
pathpilot-operations.workspace = true
pathpilot-preview.workspace = true
tracing.workspace = true
vte.workspace = true
